service:
  name: apptodo

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfi: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider: 
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /createTodo/{userId}
          method: POST
          cors: true
  listTodoFromUser:
    handler: src/functions/listTodoFromUser.handle
    events:
      - http:
          path: /listTodoFromUser/{userId}
          method: GET
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE 
